# Generated by Django 4.2.25 on 2025-11-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='player_name',
            field=models.CharField(default='Unknown Player', max_length=50),
        ),
    ]
